FROM golang:1.13.4-stretch@sha256:02ca4f0b018977a544d867e40305eb92cf41c810c80075ac60dd02cf5abc550e as build
ENV VERSION=0.34.0

# armv7
RUN apt update && apt install -y git
ARG source=https://github.com/coreos/prometheus-operator.git
ARG release=release-0.34

RUN mkdir -p /go/src/github.com/coreos/
WORKDIR /go/src/github.com/coreos/
RUN git clone --depth 1 --single-branch --branch ${release} ${source}
WORKDIR /go/src/github.com/coreos/prometheus-operator
RUN ls -lsh; git status
RUN GOOS=linux CGO_ENABLED=0 go build -mod=vendor -ldflags="-s -X github.com/coreos/prometheus-operator/pkg/version.Version=${VERSION}" -o /tmp/prometheus-config-reloader cmd/prometheus-config-reloader/main.go


# Ideally we could use the "static" flavour but let's first start with the base flavour (which has glibc).
# FROM gcr.io/distroless/base@sha256:edc3643ddf96d75032a55e240900b68b335186f1e5fea0a95af3b4cc96020b77
# armv7
FROM ubuntu:bionic@sha256:349e3988c0241304b39218794b8263325f7dc517317e00be37d43c3bdda9449b

COPY --from=build /tmp/prometheus-config-reloader /bin/prometheus-config-reloader

# On busybox 'nobody' has uid `65534'
USER 65534

ENTRYPOINT ["/bin/prometheus-config-reloader"]
